const PopularSearches = [
  "wedding",
  "flowers",
  "real estate",
  "christmas",
  "music",
  "construction",
  "background",
  "Beach",
  "heart",
  "tree",
  "Birthday",
  "spa",
  "hair",
  "house",
  "beauty",
  "landscape",
  "wine",
  "fitness",
  "car",
  "love",
  "graduation",
  "business",
  "jewelry",
  "computer",
  "fashion",
  "medical",
  "church",
  "landscaping",
  "books",
  "money",
];

const jsonImg = [
  {
    version: "1.0",
    image: {
      name: "/var/www/imageconvert_usr/data/www/imageconvert.org/image/public/uploadt/photo_editor_image - Copy.png",
      format: "json",
      formatDescription: "The image format and characteristics",
      mimeType: "application/json",
      class: "DirectClass",
      geometry: {
        width: 1000,
        height: 500,
        x: 0,
        y: 0,
      },
      units: "Undefined",
      type: "TrueColorAlpha",
      endianness: "Undefined",
      colorspace: "sRGB",
      depth: 8,
      baseDepth: 8,
      channelDepth: {
        alpha: 1,
        red: 8,
        green: 8,
        blue: 8,
      },
      pixels: 500000,
      imageStatistics: {
        all: {
          min: 0,
          max: 255,
          mean: 249.204,
          standardDeviation: 28.2294,
          kurtosis: 40.2311,
          skewness: -6.32608,
          entropy: 0.0852529,
        },
      },
      channelStatistics: {
        alpha: {
          min: 0,
          max: 0,
          mean: 0,
          standardDeviation: 0,
          kurtosis: 8.192e51,
          skewness: 1e36,
          entropy: 0,
        },
        red: {
          min: 0,
          max: 255,
          mean: 247.139,
          standardDeviation: 38.02,
          kurtosis: 28.3085,
          skewness: -5.36172,
          entropy: 0.113739,
        },
        green: {
          min: 0,
          max: 255,
          mean: 247.208,
          standardDeviation: 37.811,
          kurtosis: 28.6618,
          skewness: -5.38848,
          entropy: 0.11364,
        },
        blue: {
          min: 0,
          max: 255,
          mean: 247.47,
          standardDeviation: 37.0866,
          kurtosis: 30.0261,
          skewness: -5.48929,
          entropy: 0.113633,
        },
      },
      renderingIntent: "Perceptual",
      gamma: 0.45455,
      chromaticity: {
        redPrimary: {
          x: 0.64,
          y: 0.33,
        },
        greenPrimary: {
          x: 0.3,
          y: 0.6,
        },
        bluePrimary: {
          x: 0.15,
          y: 0.06,
        },
        whitePrimary: {
          x: 0.3127,
          y: 0.329,
        },
      },
      backgroundColor: "#FFFFFFFF",
      borderColor: "#DFDFDFFF",
      matteColor: "#BDBDBDFF",
      transparentColor: "#00000000",
      interlace: "None",
      intensity: "Undefined",
      compose: "Over",
      pageGeometry: {
        width: 1000,
        height: 500,
        x: 0,
        y: 0,
      },
      dispose: "Undefined",
      iterations: 0,
      compression: "Zip",
      orientation: "Undefined",
      properties: {
        "date:create": "2024-12-17T12:10:07+00:00",
        "date:modify": "2024-12-17T12:10:07+00:00",
        "png:cHRM": "chunk was found (see Chromaticity, above)",
        "png:gAMA": "gamma=0.45455 (See Gamma, above)",
        "png:IHDR.bit-depth-orig": "8",
        "png:IHDR.bit_depth": "8",
        "png:IHDR.color-type-orig": "6",
        "png:IHDR.color_type": "6 (RGBA)",
        "png:IHDR.interlace_method": "0 (Not interlaced)",
        "png:IHDR.width,height": "1000, 500",
        "png:sRGB": "intent=0 (Perceptual Intent)",
        signature: "cca81dfd93cd128228e465f3706ddb3cc00a7a45f8959d8788766129fa2861d0",
      },
      tainted: false,
      filesize: "48890B",
      numberPixels: "500000",
      pixelsPerSecond: "47.1808MB",
      userTime: "0.020u",
      elapsedTime: "0:01.010",
      version: "ImageMagick 6.9.11-60 Q16 x86_64 2021-01-25 https://imagemagick.org",
    },
  },
];

export { PopularSearches, jsonImg };
